import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { generateCommand, commandFilename, isGenerated, extractSource } from "../src/convert.mjs";
import { getAgent } from "../src/registry.mjs";

const mockSkill = {
  name: "team-setup",
  description: "Clone, scaffold, or configure a team AI directives repository",
  body: "# Team Setup\n\nThis is the skill body.\n\n## When to Use\n\nWhen you need to set up team directives.",
  dir: "/project/.agents/skills/team-setup",
  frontmatter: { name: "team-setup", description: "Clone, scaffold, or configure a team AI directives repository" },
};

describe("Command generation — Markdown", () => {
  it("generates inline markdown command with frontmatter", () => {
    const agent = getAgent("opencode");
    const content = generateCommand(mockSkill, agent, { mode: "inline", source: "tikalk/adlc-team-skills" });

    assert.ok(content.startsWith("---\n"));
    assert.ok(content.includes("description: Clone, scaffold, or configure"));
    assert.ok(content.includes("generated by adlc-agents-cli"));
    assert.ok(content.includes("source: tikalk/adlc-team-skills"));
    assert.ok(content.includes("# Team Setup"));
    assert.ok(content.includes("$ARGUMENTS"));
  });

  it("generates wrapper markdown command", () => {
    const agent = getAgent("opencode");
    const content = generateCommand(mockSkill, agent, { mode: "wrapper", source: "test" });

    assert.ok(content.includes("Invoke the `team-setup` skill using the `skill` tool."));
    assert.ok(content.includes("$ARGUMENTS"));
    assert.ok(!content.includes("# Team Setup"));
  });

  it("includes base directory note in inline mode", () => {
    const agent = getAgent("opencode");
    const content = generateCommand(mockSkill, agent, { mode: "inline", source: "test" });

    assert.ok(content.includes("Base directory for this skill:"));
    assert.ok(content.includes("/project/.agents/skills/team-setup"));
  });

  it("generates correct filename", () => {
    const agent = getAgent("opencode");
    assert.equal(commandFilename(mockSkill, agent, {}), "team-setup.md");

    const claudeAgent = getAgent("claude-code");
    assert.equal(commandFilename(mockSkill, claudeAgent, {}), "team-setup.md");
  });

  it("applies prefix to filename", () => {
    const agent = getAgent("opencode");
    assert.equal(commandFilename(mockSkill, agent, { prefix: "adlc" }), "adlc.team-setup.md");
  });

  it("generates .prompt.md for copilot", () => {
    const agent = getAgent("github-copilot");
    assert.equal(commandFilename(mockSkill, agent, {}), "team-setup.prompt.md");
  });

  it("generates .mdc for firebender", () => {
    const agent = getAgent("firebender");
    assert.equal(commandFilename(mockSkill, agent, {}), "team-setup.mdc");
  });
});

describe("Command generation — TOML", () => {
  it("generates TOML for gemini-cli", () => {
    const agent = getAgent("gemini-cli");
    const content = generateCommand(mockSkill, agent, { source: "test" });

    assert.ok(content.includes('description ='));
    assert.ok(content.includes('prompt = """'));
    assert.ok(content.includes("# generated by adlc-agents-cli"));
    assert.ok(content.includes("{{args}}"));
  });

  it("generates .toml filename", () => {
    const agent = getAgent("gemini-cli");
    assert.equal(commandFilename(mockSkill, agent, {}), "team-setup.toml");
  });
});

describe("Command generation — YAML", () => {
  it("generates YAML for goose", () => {
    const agent = getAgent("goose");
    const content = generateCommand(mockSkill, agent, { source: "test" });

    assert.ok(content.includes("description:"));
    assert.ok(content.includes("prompt: |"));
    assert.ok(content.includes("# generated by adlc-agents-cli"));
    assert.ok(content.includes("{{args}}"));
  });

  it("generates .yaml filename", () => {
    const agent = getAgent("goose");
    assert.equal(commandFilename(mockSkill, agent, {}), "team-setup.yaml");
  });
});

describe("Generated file detection", () => {
  it("isGenerated detects our header", () => {
    const agent = getAgent("opencode");
    const content = generateCommand(mockSkill, agent, { source: "tikalk/adlc-team-skills" });
    assert.ok(isGenerated(content));
  });

  it("isGenerated returns false for user-created files", () => {
    assert.ok(!isGenerated("# My custom command\n\nDo something."));
  });

  it("extractSource returns the source origin", () => {
    const agent = getAgent("opencode");
    const content = generateCommand(mockSkill, agent, { source: "tikalk/adlc-team-skills" });
    assert.equal(extractSource(content), "tikalk/adlc-team-skills");
  });
});
